package com.ryzhyj.inteview.config;

/*
    Just a crud
* */
public enum Combination {
    SAME_SYMBOLS, HORIZONTALLY_LINEAR_SYMBOLS, VERTICALLY_LINEAR_SYMBOLS, LTR_DIAGONALLY_LINEAR_SYMBOLS, RTL_DIAGONALLY_LINEAR_SYMBOLS
}
